using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using Newtonsoft.Json;
using PCB;

namespace EasyEDA_Loader
{
    internal sealed class StackupRecommendation
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string WhenToUse { get; set; }
        public int LayerCount { get; set; }
        public string ThicknessMm { get; set; }
        public string OuterOz { get; set; }
        public string InnerOz { get; set; }
        public string Template { get; set; }
        public string StackupFile { get; set; }
        public string LegacyStackupFile { get; set; }
        public string RulesFile { get; set; }
        public string LayerPlan { get; set; }
        public bool RecommendedDefault { get; set; }
        public double MinTraceMils { get; set; } = 4;
        public double MinClearanceMils { get; set; } = 4;
        public List<string> Caveats { get; set; } = new List<string>();
    }

    internal sealed class FabStackupPreference
    {
        public string SelectedId { get; set; } = "4l-jlc7628";
        public double MinTraceMils { get; set; } = 4;
        public double MinClearanceMils { get; set; } = 4;
        public int LayerCount { get; set; } = 4;
        public string Template { get; set; } = "JLC04161H-7628";
    }

    /// <summary>
    /// JLCPCB stackup picker + validation. Uses curated files under fab/recommended
    /// (from gsuberland + ayberkozgur GitHub libraries).
    /// </summary>
    internal static class PcbStackupAdvisor
    {
        public static string UserRecommendedDir =>
            Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                "AltiumEE",
                "recommended-stackups");

        public static string PreferencePath =>
            Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                "AltiumEE",
                "fab-preference.json");

        public static IReadOnlyList<StackupRecommendation> Catalog { get; } = new List<StackupRecommendation>
        {
            new StackupRecommendation
            {
                Id = "2l-simple",
                Title = "2-layer 1.6 mm 1 oz (simple digital)",
                WhenToUse = "Low-speed MCU boards with no RF/WiFi/LoRa and few power rails.",
                LayerCount = 2,
                ThicknessMm = "1.6",
                OuterOz = "1",
                InnerOz = "n/a",
                Template = "2L standard",
                StackupFile = "2layer-1oz-1.6mm.stackup",
                RulesFile = "2layer-1oz.RUL",
                LayerPlan = "Top = signal+parts, Bottom = GND pour (or vice versa).",
                MinTraceMils = 5,
                MinClearanceMils = 5,
                Caveats =
                {
                    "Poor RF return path — do not use for LoRa/WiFi antennas.",
                    "USB / fast edges will be noisier than 4L.",
                },
            },
            new StackupRecommendation
            {
                Id = "4l-jlc7628",
                Title = "4-layer 1.6 mm JLC04161H-7628 (recommended for ESP/LoRa)",
                WhenToUse = "ESP32, LoRa (SX1262), WiFi/BLE, USB + multiple rails — default for this plugin.",
                LayerCount = 4,
                ThicknessMm = "1.6",
                OuterOz = "1",
                InnerOz = "0.5",
                Template = "JLC04161H-7628",
                StackupFile = "jlcpcb_4L_1.6mm_outer1oz_inner0.5oz_JLC04161H-7628.stackupx",
                LegacyStackupFile = "4layer-1oz-jlc7628-1.6mm.stackup",
                RulesFile = "4layer-1oz.RUL",
                LayerPlan = "L1 Top signal/RF · L2 solid GND · L3 3v3 pour · L4 Bottom GND/signals",
                RecommendedDefault = true,
                MinTraceMils = 4,
                MinClearanceMils = 4,
                Caveats =
                {
                    "Verify impedance widths with JLCPCB calculator (RF ~50Ω microstrip depends on prepreg).",
                    "Order FR-4 TG155 if you need controlled impedance (not cheap TG135).",
                    "Autogenerated .stackupx from JLC API — spot-check thicknesses in Layer Stack Manager.",
                    "Never route foreign nets under large GND EPADs on Bottom.",
                    "Library data: ayberkozgur .stackup/.RUL are solid fab-rule baselines; gsuberland .stackupx matches JLC impedance API (spot-check before critical RF).",
                },
            },
            new StackupRecommendation
            {
                Id = "4l-noreq",
                Title = "4-layer 1.6 mm NOREQ (JLC default / no impedance)",
                WhenToUse = "Same 4L board when you are not ordering impedance control.",
                LayerCount = 4,
                ThicknessMm = "1.6",
                OuterOz = "1",
                InnerOz = "0.5",
                Template = "NOREQ",
                StackupFile = "jlcpcb_4L_1.6mm_outer1oz_inner0.5oz_NOREQ.stackupx",
                RulesFile = "4layer-1oz.RUL",
                LayerPlan = "Same plane assignment as 7628: Mid1 GND, Mid2 3v3.",
                MinTraceMils = 4,
                MinClearanceMils = 4,
                Caveats =
                {
                    "Dielectric may differ from impedance templates — avoid for critical RF matching.",
                },
            },
            new StackupRecommendation
            {
                Id = "6l-jlc7628",
                Title = "6-layer 1.6 mm JLC06161H-7628 (dense / multi-rail)",
                WhenToUse = "BGAs, many supplies, or when 4L routing is too tight.",
                LayerCount = 6,
                ThicknessMm = "1.6",
                OuterOz = "1",
                InnerOz = "0.5",
                Template = "JLC06161H-7628",
                StackupFile = "jlcpcb_6L_1.6mm_outer1oz_inner0.5oz_JLC06161H-7628.stackupx",
                RulesFile = "6layer-1oz.RUL",
                LayerPlan = "Keep continuous GND next to every high-speed/RF signal layer; dedicate at least one solid GND and one power.",
                MinTraceMils = 3.5,
                MinClearanceMils = 3.5,
                Caveats =
                {
                    "Costlier; only needed when 4L cannot route cleanly.",
                },
            },
        };

        public static StackupRecommendation GetDefaultRecommendation() =>
            Catalog.FirstOrDefault(c => c.RecommendedDefault) ?? Catalog[1];

        public static FabStackupPreference LoadPreference()
        {
            try
            {
                if (File.Exists(PreferencePath))
                {
                    var p = JsonConvert.DeserializeObject<FabStackupPreference>(File.ReadAllText(PreferencePath));
                    if (p != null)
                        return p;
                }
            }
            catch { }

            var d = GetDefaultRecommendation();
            return new FabStackupPreference
            {
                SelectedId = d.Id,
                MinTraceMils = d.MinTraceMils,
                MinClearanceMils = d.MinClearanceMils,
                LayerCount = d.LayerCount,
                Template = d.Template,
            };
        }

        public static void SavePreference(StackupRecommendation rec)
        {
            if (rec == null)
                return;
            Directory.CreateDirectory(Path.GetDirectoryName(PreferencePath) ?? ".");
            var pref = new FabStackupPreference
            {
                SelectedId = rec.Id,
                MinTraceMils = rec.MinTraceMils,
                MinClearanceMils = rec.MinClearanceMils,
                LayerCount = rec.LayerCount,
                Template = rec.Template,
            };
            File.WriteAllText(PreferencePath, JsonConvert.SerializeObject(pref, Formatting.Indented));

            // Raise MCP clearance floors to fab mins where needed.
            try
            {
                var profile = PcbRulesProfile.LoadOrCreateDefault();
                var changed = false;
                foreach (var rule in profile.ClearanceRules)
                {
                    if (rule.GapMils < rec.MinClearanceMils)
                    {
                        rule.GapMils = rec.MinClearanceMils;
                        changed = true;
                    }
                }
                if (changed)
                {
                    File.WriteAllText(
                        PcbRulesProfile.ProfilePath,
                        JsonConvert.SerializeObject(profile, Formatting.Indented));
                }
            }
            catch { }
        }

        public static string ValidateLibrarySummary()
        {
            var root = ResolveLibraryRoot();
            if (!Directory.Exists(root))
                return "Stackup library MISSING at " + root + " — run build-and-deploy.ps1.";

            var missing = new List<string>();
            var ok = 0;
            foreach (var rec in Catalog)
            {
                var modern = Path.Combine(root, rec.StackupFile ?? "");
                var legacy = string.IsNullOrEmpty(rec.LegacyStackupFile)
                    ? null
                    : Path.Combine(root, rec.LegacyStackupFile);
                var rules = string.IsNullOrEmpty(rec.RulesFile) ? null : Path.Combine(root, rec.RulesFile);
                var hasStack = File.Exists(modern) || (legacy != null && File.Exists(legacy));
                var hasRules = rules == null || File.Exists(rules);
                if (hasStack && hasRules)
                    ok++;
                else
                    missing.Add(rec.Id);
            }

            var msg = $"Library at {root}: {ok}/{Catalog.Count} presets have files.";
            if (missing.Count > 0)
                msg += " Missing: " + string.Join(", ", missing);
            else
                msg += " Data OK for curated presets. Prefer .stackupx for impedance; verify on jlcpcb.com/impedance for RF.";
            return msg;
        }

        public static string ResolveLibraryRoot()
        {
            // 1) Deployed next to the extension DLL
            try
            {
                var asm = Assembly.GetExecutingAssembly().Location;
                if (!string.IsNullOrWhiteSpace(asm))
                {
                    var dir = Path.Combine(Path.GetDirectoryName(asm) ?? string.Empty, "fab", "recommended");
                    if (Directory.Exists(dir))
                        return dir;
                }
            }
            catch { }

            // 2) User Documents copy
            if (Directory.Exists(UserRecommendedDir))
                return UserRecommendedDir;

            // 3) Dev repo path relative to common layouts
            var candidates = new[]
            {
                Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory ?? ".", "..", "..", "..", "..", "fab", "recommended")),
                Path.Combine(
                    Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
                    "Downloads", "EasyEDALoader-main", "EasyEDALoader-main", "fab", "recommended"),
            };
            foreach (var c in candidates)
            {
                try
                {
                    if (Directory.Exists(c))
                        return c;
                }
                catch { }
            }

            return UserRecommendedDir;
        }

        public static string SyncRecommendedToDocuments()
        {
            var src = ResolveLibraryRoot();
            Directory.CreateDirectory(UserRecommendedDir);
            if (!Directory.Exists(src))
                throw new DirectoryNotFoundException(
                    "Stackup library not found. Rebuild with build-and-deploy.ps1 (copies fab/recommended) or clone fab libraries.");

            foreach (var file in Directory.GetFiles(src))
            {
                var name = Path.GetFileName(file);
                File.Copy(file, Path.Combine(UserRecommendedDir, name), overwrite: true);
            }

            // Also copy from repo recommended if Resolve pointed at Documents already empty of stackupx
            return UserRecommendedDir;
        }

        public static string GetFilePath(StackupRecommendation rec, bool preferModernStackupx = true)
        {
            if (rec == null)
                throw new ArgumentNullException(nameof(rec));

            SyncRecommendedToDocuments();
            var dir = UserRecommendedDir;
            if (preferModernStackupx && !string.IsNullOrWhiteSpace(rec.StackupFile))
            {
                var p = Path.Combine(dir, rec.StackupFile);
                if (File.Exists(p))
                    return p;
            }

            if (!string.IsNullOrWhiteSpace(rec.LegacyStackupFile))
            {
                var p = Path.Combine(dir, rec.LegacyStackupFile);
                if (File.Exists(p))
                    return p;
            }

            if (!string.IsNullOrWhiteSpace(rec.StackupFile))
            {
                var p = Path.Combine(dir, rec.StackupFile);
                if (File.Exists(p))
                    return p;
            }

            throw new FileNotFoundException("Stackup file missing: " + (rec.StackupFile ?? rec.LegacyStackupFile));
        }

        public static void OpenInExplorer(string path)
        {
            if (Directory.Exists(path))
            {
                Process.Start(new ProcessStartInfo { FileName = path, UseShellExecute = true });
                return;
            }

            if (File.Exists(path))
            {
                Process.Start(new ProcessStartInfo
                {
                    FileName = "explorer.exe",
                    Arguments = "/select,\"" + path + "\"",
                    UseShellExecute = true,
                });
            }
        }

        public static int GetElectricalLayerCount(IPCB_Board board)
        {
            if (board == null)
                return 0;
            var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            AddLayers(board, board.Internal_ElectricalLayerIterator, it => it.Internal_AddFilter_ElectricalLayers(), names);
            AddLayers(board, board.Internal_SignalLayerIterator, it => it.Internal_AddFilter_SignalLayers(), names);
            AddLayers(board, board.Internal_InternalPlaneLayerIterator, it => it.Internal_AddFilter_InternalPlaneLayers(), names);
            return names.Count;
        }

        private static void AddLayers(
            IPCB_Board board,
            Func<object> createIterator,
            Action<IPCB_LayerIterator> configure,
            HashSet<string> names)
        {
            try
            {
                var iteratorObj = createIterator();
                if (iteratorObj is not IPCB_LayerIterator iterator)
                    return;
                configure(iterator);
                if (!iterator.First())
                    return;
                do
                {
                    var layer = iterator.Internal_Layer();
                    if (layer == null)
                        continue;
                    try
                    {
                        var name = board.LayerName(layer);
                        if (!string.IsNullOrWhiteSpace(name))
                            names.Add(name.Trim());
                    }
                    catch { }
                }
                while (iterator.Next());
            }
            catch { }
        }

        public static Dictionary<string, object> ValidateCurrentBoard(StackupRecommendation expected = null)
        {
            expected ??= GetDefaultRecommendation();
            var board = PcbDocumentHelper.EnsureProjectPcbBoard();
            if (board == null)
                throw new InvalidOperationException("Open a PCB document first.");

            var count = GetElectricalLayerCount(board);
            var okLayers = count == expected.LayerCount ||
                           (expected.LayerCount == 4 && count >= 4);
            var issues = new List<string>();
            if (count < expected.LayerCount)
                issues.Add($"Board has {count} electrical layers; recommendation wants {expected.LayerCount}.");
            else if (count > expected.LayerCount && expected.LayerCount == 4 && count == 6)
                issues.Add("Board is 6L while default rec is 4L — OK if intentional.");

            var summary = okLayers && issues.Count == 0
                ? $"Stackup check OK for '{expected.Title}' ({count} layers). Confirm Mid1=GND / Mid2=3v3 and load the .stackupx if thicknesses look wrong."
                : $"Stackup needs attention for '{expected.Title}': {string.Join(" ", issues)}";

            var report = new Dictionary<string, object>
            {
                ["checkedAt"] = DateTime.UtcNow.ToString("o"),
                ["pass"] = okLayers && issues.Count == 0,
                ["boardLayerCount"] = count,
                ["expectedLayerCount"] = expected.LayerCount,
                ["recommendationId"] = expected.Id,
                ["recommendationTitle"] = expected.Title,
                ["layerPlan"] = expected.LayerPlan,
                ["summary"] = summary,
                ["issues"] = issues,
                ["howToLoad"] =
                    "PCB → Design → Layer Stack Manager → File → Load Stackup From File → pick the .stackupx from Documents\\AltiumEE\\recommended-stackups",
            };

            try
            {
                var path = Path.Combine(
                    Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                    "AltiumEE",
                    "stackup_advice.json");
                Directory.CreateDirectory(Path.GetDirectoryName(path) ?? ".");
                File.WriteAllText(path, JsonConvert.SerializeObject(report, Formatting.Indented));
            }
            catch { }

            return report;
        }

        public static string FormatHowToLoad(StackupRecommendation rec)
        {
            string file;
            try { file = GetFilePath(rec); }
            catch (Exception ex) { return ex.Message; }

            return
                $"Recommended: {rec.Title}\n" +
                $"Layer plan: {rec.LayerPlan}\n\n" +
                "In Altium:\n" +
                "1. Open your .PcbDoc\n" +
                "2. Design → Layer Stack Manager\n" +
                "3. File → Load Stackup From File…\n" +
                $"4. Select:\n{file}\n\n" +
                "Then: Setup Net Classes & Rules → Place → Route → Via stitch → Full DRC.\n" +
                "When ordering at JLCPCB: match thickness/copper; use TG155 for impedance.";
        }
    }
}
